name: Build alpha package

on:
  push:
    branches:
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Logging in to GHCR
        run: docker login --username jasperdg828 --password ${{secrets.GHCR_TOKEN}} ghcr.io

      - name: Build docker container
        working-directory: .
        run: docker build -t ghcr.io/jasperdg828/classybooks:latest-alpha .

      - name: Pushing container
        run: docker push ghcr.io/jasperdg828/classybooks:latest-alpha
