name: Build react

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v1.18.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.10.0
      - run: cd client
      - run: npm i
      - run: npm i react-scripts
      - run: npm install -g create-react-app
      - run: npm run build
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
