name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
>>>>>>> 9e18729eb3c727044e4e7eac523ebea830417845
      - name: Logging in to GHCR
        run: docker login --username jasperdg828 --password ${{secrets.GHCR_TOKEN}} ghcr.io

      - name: Build docker container
        working-directory: .
        run: docker build -t ghcr.io/jasperdg828/classybooks:latest-dev .

      - name: Pushing container
        run: docker push ghcr.io/jasperdg828/classybooks:latest-dev
