name: Build main package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Logging in to GHCR
        run: docker login --username woutnerd --password ${{secrets.GHCR_TOKEN}} ghcr.io

      - name: Build docker container
        working-directory: .
        run: docker build -t ghcr.io/woutnerd/classybooks:latest .

      - name: Pushing container
        run: docker push ghcr.io/woutnerd/classybooks:latest
